### ISSUE TITLE
Ordered consumer is too slow

### ISSUE THREAD

**Issue by mtmk** [nats-io/nats.net.v2#333]
JetStream ordered consumer is significantly slower than `nats bench`.

``` csharp
using System.Diagnostics;
using NATS.Client.Core;
using NATS.Client.JetStream;

var nats = new NatsConnection();
var js = new NatsJSContext(nats);
var consumer = await js.CreateOrderedConsumerAsync("benchstream");

var count = 0;
var size = 0;
var max = 1_000_000;
var stopwatch = Stopwatch.StartNew();
await foreach (var jsMsg in consumer.ConsumeAsync<byte[]>())
{
    size += jsMsg.Size;
    if (++count == max)
        break;
}

Console.WriteLine($"{count / stopwatch.Elapsed.TotalSeconds:n0} msgs/sec ~ {(double)size / 0x100000 / stopwatch.Elapsed.TotalSeconds:n2} MB/sec");

// nats bench benchsubject --js --purge --pub 1 --msgs 1000000
//
// nats bench benchsubject --js --sub 1 --msgs 1000000
// 837,581 msgs/sec ~ 102.24 MB/sec
//
// nats bench benchsubject --js --sub 1 --msgs 1000000 --push
// 341,509 msgs/sec ~ 41.69 MB/sec
//
// nats bench benchsubject --js --sub 1 --msgs 1000000 --pull
// 203,993 msgs/sec ~ 24.90 MB/sec
//
// dotnet run
// 326,307 msgs/sec ~ 70.22 MB/sec
```

See also https://natsio.slack.com/archives/C055AB5M1KM/p1705097317008559

**Comment by to11mtm** [comment]
One potentially 'not large but low hanging fruit': https://github.com/nats-io/nats.net.v2/blob/3e3c86745008cf190e6f16d83a08a6a839adfda4/src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs#L122-L131

AFAIK there's no way this should throw an `OperationCancelledException`, or any of these other exceptions would happen (at least *logically*, by convention `Channel.TryRead`/`Channel.TryWrite` do not throw to keep things 'clean' for sync paths,) so getting rid of that try/catch block may help a bit (unless there is something I'm missing).

Other questions/ponderances:

- is the `consumer.ConsumeAsync<ReadOnlyMemory<byte>>()` scenario (even if it requires some extra plumbing) worth checking? I could easily see byte array alloc/copies eating into throughput as observed
- In general I'm noting that our `MoveNext()` state machine winds up with 32 locals.  See attached photo.
  - It may be worth investigating if this can be trimmed or optimized as a whole, since I think all of this code winds up in the state machine AFAIK.

![consumeasync](https://github.com/nats-io/nats.net.v2/assets/12536917/90e1da9b-c7c7-48e6-9ca5-49ab567ff281)

**Comment by mtmk** [comment]
quick update: experimenting with a few options to keep pull requests steadily overlapped which seems to help with the throughput. good suggestions @to11mtm thanks 🙏 will apply them as well and see if I can improve a little more.

**Comment by to11mtm** [comment]
> quick update: experimenting with a few options to keep pull requests steadily overlapped which seems to help with the throughput. good suggestions @to11mtm thanks 🙏 will apply them as well and see if I can improve a little more.

As one more added thought...

I would be genuinely curious as to the throughput if an `UnboundedChannel<T>` rather than `BoundedChannel<T>` was used internally; as the differences in locking behaviors could have an impact on this scenario. I can try to write a barebones bench (i.e. just seeing what timings are with one reader and writer doing their thing on each channel) to test first if that will help.

**Comment by mtmk** [comment]
> I would be genuinely curious as to the throughput if an `UnboundedChannel<T>` rather than `BoundedChannel<T>` was used

That did the trick! Awesome, TYVVM @to11mtm. Message rate is over 700K/s now (from 300K/s) which is close enough to nats bench performance of 800K/s.
