### ISSUE TITLE
Auto-unsubscribe options

### ISSUE THREAD

**Issue by mtmk** [nats-io/nats.net.v2#67]
Users should be able to automatically unsubscribe:
* After a certain number of messages (max-msgs)
* After a certain time period (timeout)
* Time period after the previous message was received (idle timeout)
* Also, unsubscribe explicitly (before `Dispose`)

First scenario (max-msgs) can be implemented using [UNSUB](https://docs.nats.io/reference/reference-protocols/nats-protocol#unsub) `max_msgs`:
* `SUB` then immediately `UNSUB` with `max_msgs` specified
* Keep a message `count` for subscription
* When `count == max_msgs` signal user code (e.g. end iterators) and remove subscription
* When reconnecting `UNSUB` with `max_msgs - count`

Timeouts would complete iterators and unsubscribe.

If combination of the options is used then whichever happens first wins and cancel others.

- [ ] add `Unsubscribe()` method on `NatsSub`
- [ ] add `MaxMsgs` on `SubOpts`
- [ ] add `Timeout` on `SubOpts`
- [ ] add `IdleTimeout` on `SubOpts`

**Comment by Jarema** [comment]
In Rust and Go clients, there are those methods:

Rust: `sub.unsubscribe_after(max: u64) -> Result<(), UnsubscribeError>`
Go: `func (s *Subscription) AutoUnsubscribe(max int) error`

So both are called on active subscription.
Both are also counting number of messages since the start of the subscription, and when max is already reched when setting UNSUB, it will immediately close the subscription.

If not, it will check the max internally at every message, and close subscription when counter reaches max.

For re-subscribing, you can still maintain the subscription state on the client side, and just resubscribe with the server.

**Comment by mtmk** [comment]
Currently we don't have an explicit unsubscribe method, it's done during subscription dispose. More natural way might be to add maxMsgs field to subscription options in our case.
